config/routes.rb
Notacms::Application.routes.draw do

  resources :menus

  resources :positions, only: :update

  resources :users

  resources :contents

  resources :views, only: :index

  root to: 'view#index'

end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :content, :position, :title, :top, :left, :width, :height
  attr_accessor :position_id

  PAGE_NOT_FOUND = {top: 100, left: 100, width: 200, height: 100, title: 'Page not found', content: 'Page not found'}

  has_many :positions, dependent: :destroy
  has_many :menus, dependent: :destroy

  def self.get_meme content_id, user_id
    user = User.find_by_id(user_id)
    if user
      content = Content.find_by_id(content_id)
      if content
        position = Position.find_by_user_id_and_content_id(user.id, content.id)
        if position
          content.top = position.top
          content.left = position.left
          content.width = position.width
          content.height = position.height
        else
          position = Position.create(user_id: user.id, content_id: content.id, top: content.top, left: content.left, width: content.width, height: content.height)
          content.position_id = position.id
        end
        content.attributes.merge('position_id' => position.id)
      else
        PAGE_NOT_FOUND
      end
    end
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :content
  attr_accessible :name, :parent_id, :content

  def content_text
    (name.blank? and content.try(:title).to_s or name).gsub(' ', '&nbsp;').html_safe
  end
end

app/models/position.rb
class Position < ActiveRecord::Base
  belongs_to :content
  belongs_to :user
  attr_accessible :height, :left, :minimised, :top, :width, :user_id, :content_id
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name

  has_many :positions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contents }
    end
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @content = Content.get_meme params[:id], cookies[:notacms]
    render json: @content.to_json
  end

  # GET /contents/new
  # GET /contents/new.json
  def new
    @content = Content.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content }
    end
  end

  # GET /contents/1/edit
  def edit
    @content = Content.find(params[:id])
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(params[:content])

    respond_to do |format|
      if @content.save
        format.html { redirect_to @content, notice: 'Page was successfully created.' }
        format.json { render json: @content, status: :created, location: @content }
      else
        format.html { render action: "new" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contents/1
  # PUT /contents/1.json
  def update
    @content = Content.find(params[:id])

    respond_to do |format|
      if @content.update_attributes(params[:content])
        format.html { redirect_to @content, notice: 'Page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content = Content.find(params[:id])
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController

  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(params[:menu])

    if @menu.save
      redirect_to menu_path(@menu), notice: 'Menu was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    @menu = Menu.find(params[:id])

    if @menu.update_attributes(params[:menu])
      redirect_to menu_path(@menu), notice: 'Menu was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @menu = Menu.find(params[:id])
    @menu.destroy

    redirect_to menus_path
  end
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  # PUT /positions/1.json
  def update
    @position = Position.find(params[:id])
    Rails.logger.info @position.inspect
    Rails.logger.info params[:position].inspect
    respond_to do |format|
      if @position.update_attributes(params[:position])
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  def index
    @user = User.find_or_create_by_id(cookies[:notacms])
    cookies[:notacms] = @user.id
    @contents = @user.positions.map {|position| Content.get_meme(position.content, cookies[:notacms])}
    @menus = Menu.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/Contents/_form.html.haml
= form_for @content do |f|
  - if @content.errors.any?
    #error_explanation
      %h2= "#{pluralize(@content.errors.count, "error")} prohibited this content from being saved:"
      %ul
        - @content.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :top
    = f.text_field :top
  .field
    = f.label :left
    = f.text_field :left
  .field
    = f.label :width
    = f.text_field :width
  .field
    = f.label :height
    = f.text_field :height
  .actions
    = f.submit 'Save'

app/views/Contents/edit.html.haml
%h1 Editing content

= render 'form'

= link_to 'Show', @content
\|
= link_to 'Back', contents_path

app/views/Contents/index.html.haml
%h1 Listing contents

%table
  %tr
    %th ID
    %th Title
    -#%th Content
    %th top
    %th left
    %th width
    %th height
    %th
    %th
    %th

  - @contents.each do |content|
    %tr
      %td= content.id
      %td= content.title
      -#%td= content.content
      %td= content.top
      %td= content.left
      %td= content.width
      %td= content.height
      %td= link_to 'Show', content
      %td= link_to 'Edit', edit_content_path(content)
      %td= link_to 'Destroy', content, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Page', new_content_path

app/views/Contents/new.html.haml
%h1 New content

= render 'form'

= link_to 'Back', contents_path

app/views/Contents/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @content.title
%p
  %b Content:
  = @content.content
%p
  %b Position:
  = @content.position

= link_to 'Edit', edit_content_path(@content)
\|
= link_to 'Back', contents_path

app/views/layouts/application.html.erb
<%= yield %>

app/views/menus/_form.html.haml
= form_for @menu do |f|
  - if @menu.errors.any?
    #error_explanation
      %h2= "#{pluralize(@menu.errors.count, 'error')} prohibited this menu from being saved:"
      %ul
        - @menu.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :parent_id
    = f.number_field :parent_id
  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/menus/edit.html.haml
%h1 Editing menu

= render 'form'

= link_to 'Cancel', menu_path(@menu), id: :cancel_edit_menu_link

app/views/menus/index.html.haml
%h1 Listing menus

%table
  %tr
    %th Parent
    %th Content
    %th Name

  - @menus.each do |menu|
    %tr
      %td= link_to menu.parent_id, menu_path(menu)
      %td= menu.content
      %td= menu.name

%br

= link_to 'New Menu', new_menu_path, id: :new_menu_link

app/views/menus/new.html.haml
%h1 New menu

= render 'form'

= link_to 'Cancel', menus_path, id: :cancel_new_menu_link

app/views/menus/show.html.haml
%p#notice= notice

%p
  %b Parent:
  = @menu.parent_id
%p
  %b Content:
  = @menu.content
%p
  %b Name:
  = @menu.name

= link_to 'Edit', edit_menu_path(@menu), id: :edit_menu_link

app/views/pages/_form.html.haml
= form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :top
    = f.text_field :top
  .field
    = f.label :left
    = f.text_field :left
  .field
    = f.label :width
    = f.text_field :width
  .field
    = f.label :height
    = f.text_field :height
  .actions
    = f.submit 'Save'

app/views/positions/_form.html.haml
= form_for @position do |f|
  - if @position.errors.any?
    #error_explanation
      %h2= "#{pluralize(@position.errors.count, "error")} prohibited this position from being saved:"
      %ul
        - @position.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_field :content
  .field
    = f.label :user_id
    = f.text_field :user_id
  .field
    = f.label :top
    = f.number_field :top
  .field
    = f.label :left
    = f.number_field :left
  .field
    = f.label :width
    = f.number_field :width
  .field
    = f.label :height
    = f.number_field :height
  .field
    = f.label :minimised
    = f.check_box :minimised
  .actions
    = f.submit 'Save'

app/views/positions/edit.html.haml
%h1 Editing position

= render 'form'

= link_to 'Show', @position
\|
= link_to 'Back', positions_path

app/views/positions/index.html.haml
%h1 Listing positions

%table
  %tr
    %th Page
    %th User
    %th Top
    %th Left
    %th Width
    %th Height
    %th Minimised
    %th
    %th
    %th

  - @positions.each do |position|
    %tr
      %td= position.content
      %td= position.user_id
      %td= position.top
      %td= position.left
      %td= position.width
      %td= position.height
      %td= position.minimised
      %td= link_to 'Show', position
      %td= link_to 'Edit', edit_position_path(position)
      %td= link_to 'Destroy', position, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Position', new_position_path

app/views/positions/new.html.haml
%h1 New position

= render 'form'

= link_to 'Back', positions_path

app/views/positions/show.html.haml
%p#notice= notice

%p
  %b Page:
  = @position.content
%p
  %b User:
  = @position.user_id
%p
  %b Top:
  = @position.top
%p
  %b Left:
  = @position.left
%p
  %b Width:
  = @position.width
%p
  %b Height:
  = @position.height
%p
  %b Minimised:
  = @position.minimised

= link_to 'Edit', edit_position_path(@position)
\|
= link_to 'Back', positions_path

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %tr
    %th Name
    %th Email
    %th
    %th
    %th

  - @users.each do |user|
    %tr
      %td= user.name
      %td= user.email
      %td= link_to 'Show', user
      %td= link_to 'Edit', edit_user_path(user)
      %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @user.name
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path

app/views/views/index.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <link rel="stylesheet" type="text/css" href="/assets/start/jquery-ui-1.10.3.custom.css"/>
  <link rel="stylesheet" type="text/css" href="/assets/jquery.taskbar.css"/>

  <script src="/assets/jquery-1.9.1.js"></script>
  <script src="/assets/jquery-ui-1.10.3.custom.js"></script>
  <script src="/assets/jquery.taskbar.js"></script>
  <script>
      $(function () {

          var contents = [];

          <% @contents.each do |content| %>
          contents.push(<%= content.to_json.to_s.html_safe %>);
          <% end %>

          contents.forEach(function (content) {
              var dialog = $("#dialog").clone().attr("id", "dialog" + content.id);
              createWindow(content, dialog)
          });

          $('#menu').css('position', 'relative').menu().css('z-index', 3000);
          function createWindow(data, dialog) {
              console.log(data);
              if (data == null) {
                  $(location).attr('href', '/views');
              }
              else {
                  dialog.attr("title", data.title, 'data', 1).data("position_id", data.position_id).append(data.content).taskbardialog({
                      taskbar: "#taskbar",
                      height: data.height,
                      width: data.width,
                      position: [data.left, data.top],
                      dragStop: function (event, ui) {
                          var pos_id = $(this).data('position_id');
                          console.log("dragStop", ui.position.left);
                          $.ajax({url: 'positions/' + pos_id + '.json', type: "PUT", data: { position: {top: ui.position.top, left: ui.position.left}}})
                      },
                      resizeStop: function (event, ui) {
                          var pos_id = $(this).data('position_id');
                          console.log("resizeStop", ui.size);
                          console.log(ui);
                          $.ajax({url: 'positions/' + pos_id + '.json', type: "PUT", data: { position: {width: ui.size.width, height: ui.size.height}}})
                      }
                  });
              }
          }

          $(".makedlg").click(function (event) {
              var i = event.currentTarget.id;

              if ($('#dialog' + i).taskbardialog('isOpen') === true) {
                  return
              }
              var dialog = $("#dialog").clone().attr("id", "dialog" + i);
              var url = 'contents/' + i + '.json';
              $.getJSON(url, function (data) {
                  createWindow(data, dialog);
              });

              console.log($("#dialog" + i).taskbardialog("option", "title"));
              console.log(dialog.position());
          });
      });
  </script>
  <style type="text/css">
      body {
          margin: 0;
          padding: 0;
      }
  </style>
</head>
<body>


<ul id='menu'>

  <li><a href='#'>Start</a>
    <ul>
      <% @menus.each do |menu| %>
          <li>
            <a href='#' class="makedlg" id='<%= menu.content_id %>'><%= menu.content_text %></a>
          </li>
      <% end %>
    </ul>
  </li>
</ul>

<div id="dialog" class="buzzilla" title="buzzilla dialog" style="display: none">
</div>

<div id="taskbar" style="width: 220px; position:relative; float:right; z-index: 3000; border: 1px solid black">
  <span class="taskbar">Taskbar (cookie <%= @cookie %>)</span>
</div>
</body>
</html>